dataset:
  datasets_directory: "/opt/RY-SlopeSearch/example/example_data/assembled-ecoli"

parameters:
  using_one_to_one_matching: true
  using_background_matches: false
  use_openmp: true

# methods
#   basic_kmer_matches
#   start_ry_matches
#   start_ry_4_6_matches
#   start_ry_4_9_matches
#   start_ry_16_matches
#   start_ry_32_matches
#   start_ry_64_matches
#   start_ry_128_matches
sampling_method: "start_ry_128_matches"

output_directory: "/out"

use_progress_bar: true
